// Code generated by ent, DO NOT EDIT.

package projects

import (
	"project-manager/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Projects {
	return predicate.Projects(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Projects {
	return predicate.Projects(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Projects {
	return predicate.Projects(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Projects {
	return predicate.Projects(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Projects {
	return predicate.Projects(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Projects {
	return predicate.Projects(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Projects {
	return predicate.Projects(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Projects {
	return predicate.Projects(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Projects {
	return predicate.Projects(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Projects {
	return predicate.Projects(sql.FieldEQ(FieldName, v))
}

// ImageUrl applies equality check predicate on the "imageUrl" field. It's identical to ImageUrlEQ.
func ImageUrl(v string) predicate.Projects {
	return predicate.Projects(sql.FieldEQ(FieldImageUrl, v))
}

// Link applies equality check predicate on the "link" field. It's identical to LinkEQ.
func Link(v string) predicate.Projects {
	return predicate.Projects(sql.FieldEQ(FieldLink, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Projects {
	return predicate.Projects(sql.FieldEQ(FieldDescription, v))
}

// Stacks applies equality check predicate on the "stacks" field. It's identical to StacksEQ.
func Stacks(v string) predicate.Projects {
	return predicate.Projects(sql.FieldEQ(FieldStacks, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Projects {
	return predicate.Projects(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Projects {
	return predicate.Projects(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Projects {
	return predicate.Projects(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Projects {
	return predicate.Projects(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Projects {
	return predicate.Projects(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Projects {
	return predicate.Projects(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Projects {
	return predicate.Projects(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Projects {
	return predicate.Projects(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Projects {
	return predicate.Projects(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Projects {
	return predicate.Projects(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Projects {
	return predicate.Projects(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Projects {
	return predicate.Projects(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Projects {
	return predicate.Projects(sql.FieldContainsFold(FieldName, v))
}

// ImageUrlEQ applies the EQ predicate on the "imageUrl" field.
func ImageUrlEQ(v string) predicate.Projects {
	return predicate.Projects(sql.FieldEQ(FieldImageUrl, v))
}

// ImageUrlNEQ applies the NEQ predicate on the "imageUrl" field.
func ImageUrlNEQ(v string) predicate.Projects {
	return predicate.Projects(sql.FieldNEQ(FieldImageUrl, v))
}

// ImageUrlIn applies the In predicate on the "imageUrl" field.
func ImageUrlIn(vs ...string) predicate.Projects {
	return predicate.Projects(sql.FieldIn(FieldImageUrl, vs...))
}

// ImageUrlNotIn applies the NotIn predicate on the "imageUrl" field.
func ImageUrlNotIn(vs ...string) predicate.Projects {
	return predicate.Projects(sql.FieldNotIn(FieldImageUrl, vs...))
}

// ImageUrlGT applies the GT predicate on the "imageUrl" field.
func ImageUrlGT(v string) predicate.Projects {
	return predicate.Projects(sql.FieldGT(FieldImageUrl, v))
}

// ImageUrlGTE applies the GTE predicate on the "imageUrl" field.
func ImageUrlGTE(v string) predicate.Projects {
	return predicate.Projects(sql.FieldGTE(FieldImageUrl, v))
}

// ImageUrlLT applies the LT predicate on the "imageUrl" field.
func ImageUrlLT(v string) predicate.Projects {
	return predicate.Projects(sql.FieldLT(FieldImageUrl, v))
}

// ImageUrlLTE applies the LTE predicate on the "imageUrl" field.
func ImageUrlLTE(v string) predicate.Projects {
	return predicate.Projects(sql.FieldLTE(FieldImageUrl, v))
}

// ImageUrlContains applies the Contains predicate on the "imageUrl" field.
func ImageUrlContains(v string) predicate.Projects {
	return predicate.Projects(sql.FieldContains(FieldImageUrl, v))
}

// ImageUrlHasPrefix applies the HasPrefix predicate on the "imageUrl" field.
func ImageUrlHasPrefix(v string) predicate.Projects {
	return predicate.Projects(sql.FieldHasPrefix(FieldImageUrl, v))
}

// ImageUrlHasSuffix applies the HasSuffix predicate on the "imageUrl" field.
func ImageUrlHasSuffix(v string) predicate.Projects {
	return predicate.Projects(sql.FieldHasSuffix(FieldImageUrl, v))
}

// ImageUrlIsNil applies the IsNil predicate on the "imageUrl" field.
func ImageUrlIsNil() predicate.Projects {
	return predicate.Projects(sql.FieldIsNull(FieldImageUrl))
}

// ImageUrlNotNil applies the NotNil predicate on the "imageUrl" field.
func ImageUrlNotNil() predicate.Projects {
	return predicate.Projects(sql.FieldNotNull(FieldImageUrl))
}

// ImageUrlEqualFold applies the EqualFold predicate on the "imageUrl" field.
func ImageUrlEqualFold(v string) predicate.Projects {
	return predicate.Projects(sql.FieldEqualFold(FieldImageUrl, v))
}

// ImageUrlContainsFold applies the ContainsFold predicate on the "imageUrl" field.
func ImageUrlContainsFold(v string) predicate.Projects {
	return predicate.Projects(sql.FieldContainsFold(FieldImageUrl, v))
}

// LinkEQ applies the EQ predicate on the "link" field.
func LinkEQ(v string) predicate.Projects {
	return predicate.Projects(sql.FieldEQ(FieldLink, v))
}

// LinkNEQ applies the NEQ predicate on the "link" field.
func LinkNEQ(v string) predicate.Projects {
	return predicate.Projects(sql.FieldNEQ(FieldLink, v))
}

// LinkIn applies the In predicate on the "link" field.
func LinkIn(vs ...string) predicate.Projects {
	return predicate.Projects(sql.FieldIn(FieldLink, vs...))
}

// LinkNotIn applies the NotIn predicate on the "link" field.
func LinkNotIn(vs ...string) predicate.Projects {
	return predicate.Projects(sql.FieldNotIn(FieldLink, vs...))
}

// LinkGT applies the GT predicate on the "link" field.
func LinkGT(v string) predicate.Projects {
	return predicate.Projects(sql.FieldGT(FieldLink, v))
}

// LinkGTE applies the GTE predicate on the "link" field.
func LinkGTE(v string) predicate.Projects {
	return predicate.Projects(sql.FieldGTE(FieldLink, v))
}

// LinkLT applies the LT predicate on the "link" field.
func LinkLT(v string) predicate.Projects {
	return predicate.Projects(sql.FieldLT(FieldLink, v))
}

// LinkLTE applies the LTE predicate on the "link" field.
func LinkLTE(v string) predicate.Projects {
	return predicate.Projects(sql.FieldLTE(FieldLink, v))
}

// LinkContains applies the Contains predicate on the "link" field.
func LinkContains(v string) predicate.Projects {
	return predicate.Projects(sql.FieldContains(FieldLink, v))
}

// LinkHasPrefix applies the HasPrefix predicate on the "link" field.
func LinkHasPrefix(v string) predicate.Projects {
	return predicate.Projects(sql.FieldHasPrefix(FieldLink, v))
}

// LinkHasSuffix applies the HasSuffix predicate on the "link" field.
func LinkHasSuffix(v string) predicate.Projects {
	return predicate.Projects(sql.FieldHasSuffix(FieldLink, v))
}

// LinkIsNil applies the IsNil predicate on the "link" field.
func LinkIsNil() predicate.Projects {
	return predicate.Projects(sql.FieldIsNull(FieldLink))
}

// LinkNotNil applies the NotNil predicate on the "link" field.
func LinkNotNil() predicate.Projects {
	return predicate.Projects(sql.FieldNotNull(FieldLink))
}

// LinkEqualFold applies the EqualFold predicate on the "link" field.
func LinkEqualFold(v string) predicate.Projects {
	return predicate.Projects(sql.FieldEqualFold(FieldLink, v))
}

// LinkContainsFold applies the ContainsFold predicate on the "link" field.
func LinkContainsFold(v string) predicate.Projects {
	return predicate.Projects(sql.FieldContainsFold(FieldLink, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Projects {
	return predicate.Projects(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Projects {
	return predicate.Projects(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Projects {
	return predicate.Projects(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Projects {
	return predicate.Projects(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Projects {
	return predicate.Projects(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Projects {
	return predicate.Projects(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Projects {
	return predicate.Projects(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Projects {
	return predicate.Projects(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Projects {
	return predicate.Projects(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Projects {
	return predicate.Projects(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Projects {
	return predicate.Projects(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Projects {
	return predicate.Projects(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Projects {
	return predicate.Projects(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Projects {
	return predicate.Projects(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Projects {
	return predicate.Projects(sql.FieldContainsFold(FieldDescription, v))
}

// StacksEQ applies the EQ predicate on the "stacks" field.
func StacksEQ(v string) predicate.Projects {
	return predicate.Projects(sql.FieldEQ(FieldStacks, v))
}

// StacksNEQ applies the NEQ predicate on the "stacks" field.
func StacksNEQ(v string) predicate.Projects {
	return predicate.Projects(sql.FieldNEQ(FieldStacks, v))
}

// StacksIn applies the In predicate on the "stacks" field.
func StacksIn(vs ...string) predicate.Projects {
	return predicate.Projects(sql.FieldIn(FieldStacks, vs...))
}

// StacksNotIn applies the NotIn predicate on the "stacks" field.
func StacksNotIn(vs ...string) predicate.Projects {
	return predicate.Projects(sql.FieldNotIn(FieldStacks, vs...))
}

// StacksGT applies the GT predicate on the "stacks" field.
func StacksGT(v string) predicate.Projects {
	return predicate.Projects(sql.FieldGT(FieldStacks, v))
}

// StacksGTE applies the GTE predicate on the "stacks" field.
func StacksGTE(v string) predicate.Projects {
	return predicate.Projects(sql.FieldGTE(FieldStacks, v))
}

// StacksLT applies the LT predicate on the "stacks" field.
func StacksLT(v string) predicate.Projects {
	return predicate.Projects(sql.FieldLT(FieldStacks, v))
}

// StacksLTE applies the LTE predicate on the "stacks" field.
func StacksLTE(v string) predicate.Projects {
	return predicate.Projects(sql.FieldLTE(FieldStacks, v))
}

// StacksContains applies the Contains predicate on the "stacks" field.
func StacksContains(v string) predicate.Projects {
	return predicate.Projects(sql.FieldContains(FieldStacks, v))
}

// StacksHasPrefix applies the HasPrefix predicate on the "stacks" field.
func StacksHasPrefix(v string) predicate.Projects {
	return predicate.Projects(sql.FieldHasPrefix(FieldStacks, v))
}

// StacksHasSuffix applies the HasSuffix predicate on the "stacks" field.
func StacksHasSuffix(v string) predicate.Projects {
	return predicate.Projects(sql.FieldHasSuffix(FieldStacks, v))
}

// StacksEqualFold applies the EqualFold predicate on the "stacks" field.
func StacksEqualFold(v string) predicate.Projects {
	return predicate.Projects(sql.FieldEqualFold(FieldStacks, v))
}

// StacksContainsFold applies the ContainsFold predicate on the "stacks" field.
func StacksContainsFold(v string) predicate.Projects {
	return predicate.Projects(sql.FieldContainsFold(FieldStacks, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Projects) predicate.Projects {
	return predicate.Projects(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Projects) predicate.Projects {
	return predicate.Projects(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Projects) predicate.Projects {
	return predicate.Projects(sql.NotPredicates(p))
}
