// Code generated by ent, DO NOT EDIT.

package clients

import (
	"project-manager/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Clients {
	return predicate.Clients(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Clients {
	return predicate.Clients(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Clients {
	return predicate.Clients(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Clients {
	return predicate.Clients(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Clients {
	return predicate.Clients(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Clients {
	return predicate.Clients(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Clients {
	return predicate.Clients(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Clients {
	return predicate.Clients(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Clients {
	return predicate.Clients(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Clients {
	return predicate.Clients(sql.FieldEQ(FieldName, v))
}

// Link applies equality check predicate on the "link" field. It's identical to LinkEQ.
func Link(v string) predicate.Clients {
	return predicate.Clients(sql.FieldEQ(FieldLink, v))
}

// ImageUrl applies equality check predicate on the "imageUrl" field. It's identical to ImageUrlEQ.
func ImageUrl(v string) predicate.Clients {
	return predicate.Clients(sql.FieldEQ(FieldImageUrl, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Clients {
	return predicate.Clients(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Clients {
	return predicate.Clients(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Clients {
	return predicate.Clients(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Clients {
	return predicate.Clients(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Clients {
	return predicate.Clients(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Clients {
	return predicate.Clients(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Clients {
	return predicate.Clients(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Clients {
	return predicate.Clients(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Clients {
	return predicate.Clients(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Clients {
	return predicate.Clients(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Clients {
	return predicate.Clients(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Clients {
	return predicate.Clients(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Clients {
	return predicate.Clients(sql.FieldContainsFold(FieldName, v))
}

// LinkEQ applies the EQ predicate on the "link" field.
func LinkEQ(v string) predicate.Clients {
	return predicate.Clients(sql.FieldEQ(FieldLink, v))
}

// LinkNEQ applies the NEQ predicate on the "link" field.
func LinkNEQ(v string) predicate.Clients {
	return predicate.Clients(sql.FieldNEQ(FieldLink, v))
}

// LinkIn applies the In predicate on the "link" field.
func LinkIn(vs ...string) predicate.Clients {
	return predicate.Clients(sql.FieldIn(FieldLink, vs...))
}

// LinkNotIn applies the NotIn predicate on the "link" field.
func LinkNotIn(vs ...string) predicate.Clients {
	return predicate.Clients(sql.FieldNotIn(FieldLink, vs...))
}

// LinkGT applies the GT predicate on the "link" field.
func LinkGT(v string) predicate.Clients {
	return predicate.Clients(sql.FieldGT(FieldLink, v))
}

// LinkGTE applies the GTE predicate on the "link" field.
func LinkGTE(v string) predicate.Clients {
	return predicate.Clients(sql.FieldGTE(FieldLink, v))
}

// LinkLT applies the LT predicate on the "link" field.
func LinkLT(v string) predicate.Clients {
	return predicate.Clients(sql.FieldLT(FieldLink, v))
}

// LinkLTE applies the LTE predicate on the "link" field.
func LinkLTE(v string) predicate.Clients {
	return predicate.Clients(sql.FieldLTE(FieldLink, v))
}

// LinkContains applies the Contains predicate on the "link" field.
func LinkContains(v string) predicate.Clients {
	return predicate.Clients(sql.FieldContains(FieldLink, v))
}

// LinkHasPrefix applies the HasPrefix predicate on the "link" field.
func LinkHasPrefix(v string) predicate.Clients {
	return predicate.Clients(sql.FieldHasPrefix(FieldLink, v))
}

// LinkHasSuffix applies the HasSuffix predicate on the "link" field.
func LinkHasSuffix(v string) predicate.Clients {
	return predicate.Clients(sql.FieldHasSuffix(FieldLink, v))
}

// LinkIsNil applies the IsNil predicate on the "link" field.
func LinkIsNil() predicate.Clients {
	return predicate.Clients(sql.FieldIsNull(FieldLink))
}

// LinkNotNil applies the NotNil predicate on the "link" field.
func LinkNotNil() predicate.Clients {
	return predicate.Clients(sql.FieldNotNull(FieldLink))
}

// LinkEqualFold applies the EqualFold predicate on the "link" field.
func LinkEqualFold(v string) predicate.Clients {
	return predicate.Clients(sql.FieldEqualFold(FieldLink, v))
}

// LinkContainsFold applies the ContainsFold predicate on the "link" field.
func LinkContainsFold(v string) predicate.Clients {
	return predicate.Clients(sql.FieldContainsFold(FieldLink, v))
}

// ImageUrlEQ applies the EQ predicate on the "imageUrl" field.
func ImageUrlEQ(v string) predicate.Clients {
	return predicate.Clients(sql.FieldEQ(FieldImageUrl, v))
}

// ImageUrlNEQ applies the NEQ predicate on the "imageUrl" field.
func ImageUrlNEQ(v string) predicate.Clients {
	return predicate.Clients(sql.FieldNEQ(FieldImageUrl, v))
}

// ImageUrlIn applies the In predicate on the "imageUrl" field.
func ImageUrlIn(vs ...string) predicate.Clients {
	return predicate.Clients(sql.FieldIn(FieldImageUrl, vs...))
}

// ImageUrlNotIn applies the NotIn predicate on the "imageUrl" field.
func ImageUrlNotIn(vs ...string) predicate.Clients {
	return predicate.Clients(sql.FieldNotIn(FieldImageUrl, vs...))
}

// ImageUrlGT applies the GT predicate on the "imageUrl" field.
func ImageUrlGT(v string) predicate.Clients {
	return predicate.Clients(sql.FieldGT(FieldImageUrl, v))
}

// ImageUrlGTE applies the GTE predicate on the "imageUrl" field.
func ImageUrlGTE(v string) predicate.Clients {
	return predicate.Clients(sql.FieldGTE(FieldImageUrl, v))
}

// ImageUrlLT applies the LT predicate on the "imageUrl" field.
func ImageUrlLT(v string) predicate.Clients {
	return predicate.Clients(sql.FieldLT(FieldImageUrl, v))
}

// ImageUrlLTE applies the LTE predicate on the "imageUrl" field.
func ImageUrlLTE(v string) predicate.Clients {
	return predicate.Clients(sql.FieldLTE(FieldImageUrl, v))
}

// ImageUrlContains applies the Contains predicate on the "imageUrl" field.
func ImageUrlContains(v string) predicate.Clients {
	return predicate.Clients(sql.FieldContains(FieldImageUrl, v))
}

// ImageUrlHasPrefix applies the HasPrefix predicate on the "imageUrl" field.
func ImageUrlHasPrefix(v string) predicate.Clients {
	return predicate.Clients(sql.FieldHasPrefix(FieldImageUrl, v))
}

// ImageUrlHasSuffix applies the HasSuffix predicate on the "imageUrl" field.
func ImageUrlHasSuffix(v string) predicate.Clients {
	return predicate.Clients(sql.FieldHasSuffix(FieldImageUrl, v))
}

// ImageUrlIsNil applies the IsNil predicate on the "imageUrl" field.
func ImageUrlIsNil() predicate.Clients {
	return predicate.Clients(sql.FieldIsNull(FieldImageUrl))
}

// ImageUrlNotNil applies the NotNil predicate on the "imageUrl" field.
func ImageUrlNotNil() predicate.Clients {
	return predicate.Clients(sql.FieldNotNull(FieldImageUrl))
}

// ImageUrlEqualFold applies the EqualFold predicate on the "imageUrl" field.
func ImageUrlEqualFold(v string) predicate.Clients {
	return predicate.Clients(sql.FieldEqualFold(FieldImageUrl, v))
}

// ImageUrlContainsFold applies the ContainsFold predicate on the "imageUrl" field.
func ImageUrlContainsFold(v string) predicate.Clients {
	return predicate.Clients(sql.FieldContainsFold(FieldImageUrl, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Clients {
	return predicate.Clients(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Clients) predicate.Clients {
	return predicate.Clients(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Clients) predicate.Clients {
	return predicate.Clients(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Clients) predicate.Clients {
	return predicate.Clients(sql.NotPredicates(p))
}
