// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"project-manager/ent/clients"
	"project-manager/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ClientsUpdate is the builder for updating Clients entities.
type ClientsUpdate struct {
	config
	hooks    []Hook
	mutation *ClientsMutation
}

// Where appends a list predicates to the ClientsUpdate builder.
func (cu *ClientsUpdate) Where(ps ...predicate.Clients) *ClientsUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetName sets the "name" field.
func (cu *ClientsUpdate) SetName(s string) *ClientsUpdate {
	cu.mutation.SetName(s)
	return cu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (cu *ClientsUpdate) SetNillableName(s *string) *ClientsUpdate {
	if s != nil {
		cu.SetName(*s)
	}
	return cu
}

// SetLink sets the "link" field.
func (cu *ClientsUpdate) SetLink(s string) *ClientsUpdate {
	cu.mutation.SetLink(s)
	return cu
}

// SetNillableLink sets the "link" field if the given value is not nil.
func (cu *ClientsUpdate) SetNillableLink(s *string) *ClientsUpdate {
	if s != nil {
		cu.SetLink(*s)
	}
	return cu
}

// ClearLink clears the value of the "link" field.
func (cu *ClientsUpdate) ClearLink() *ClientsUpdate {
	cu.mutation.ClearLink()
	return cu
}

// SetImageUrl sets the "imageUrl" field.
func (cu *ClientsUpdate) SetImageUrl(s string) *ClientsUpdate {
	cu.mutation.SetImageUrl(s)
	return cu
}

// SetNillableImageUrl sets the "imageUrl" field if the given value is not nil.
func (cu *ClientsUpdate) SetNillableImageUrl(s *string) *ClientsUpdate {
	if s != nil {
		cu.SetImageUrl(*s)
	}
	return cu
}

// ClearImageUrl clears the value of the "imageUrl" field.
func (cu *ClientsUpdate) ClearImageUrl() *ClientsUpdate {
	cu.mutation.ClearImageUrl()
	return cu
}

// SetCreatedAt sets the "created_at" field.
func (cu *ClientsUpdate) SetCreatedAt(t time.Time) *ClientsUpdate {
	cu.mutation.SetCreatedAt(t)
	return cu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cu *ClientsUpdate) SetNillableCreatedAt(t *time.Time) *ClientsUpdate {
	if t != nil {
		cu.SetCreatedAt(*t)
	}
	return cu
}

// SetUpdatedAt sets the "updated_at" field.
func (cu *ClientsUpdate) SetUpdatedAt(t time.Time) *ClientsUpdate {
	cu.mutation.SetUpdatedAt(t)
	return cu
}

// Mutation returns the ClientsMutation object of the builder.
func (cu *ClientsUpdate) Mutation() *ClientsMutation {
	return cu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *ClientsUpdate) Save(ctx context.Context) (int, error) {
	cu.defaults()
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *ClientsUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *ClientsUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *ClientsUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cu *ClientsUpdate) defaults() {
	if _, ok := cu.mutation.UpdatedAt(); !ok {
		v := clients.UpdateDefaultUpdatedAt()
		cu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *ClientsUpdate) check() error {
	if v, ok := cu.mutation.Name(); ok {
		if err := clients.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Clients.name": %w`, err)}
		}
	}
	return nil
}

func (cu *ClientsUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := cu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(clients.Table, clients.Columns, sqlgraph.NewFieldSpec(clients.FieldID, field.TypeInt))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Name(); ok {
		_spec.SetField(clients.FieldName, field.TypeString, value)
	}
	if value, ok := cu.mutation.Link(); ok {
		_spec.SetField(clients.FieldLink, field.TypeString, value)
	}
	if cu.mutation.LinkCleared() {
		_spec.ClearField(clients.FieldLink, field.TypeString)
	}
	if value, ok := cu.mutation.ImageUrl(); ok {
		_spec.SetField(clients.FieldImageUrl, field.TypeString, value)
	}
	if cu.mutation.ImageUrlCleared() {
		_spec.ClearField(clients.FieldImageUrl, field.TypeString)
	}
	if value, ok := cu.mutation.CreatedAt(); ok {
		_spec.SetField(clients.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := cu.mutation.UpdatedAt(); ok {
		_spec.SetField(clients.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{clients.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// ClientsUpdateOne is the builder for updating a single Clients entity.
type ClientsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ClientsMutation
}

// SetName sets the "name" field.
func (cuo *ClientsUpdateOne) SetName(s string) *ClientsUpdateOne {
	cuo.mutation.SetName(s)
	return cuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (cuo *ClientsUpdateOne) SetNillableName(s *string) *ClientsUpdateOne {
	if s != nil {
		cuo.SetName(*s)
	}
	return cuo
}

// SetLink sets the "link" field.
func (cuo *ClientsUpdateOne) SetLink(s string) *ClientsUpdateOne {
	cuo.mutation.SetLink(s)
	return cuo
}

// SetNillableLink sets the "link" field if the given value is not nil.
func (cuo *ClientsUpdateOne) SetNillableLink(s *string) *ClientsUpdateOne {
	if s != nil {
		cuo.SetLink(*s)
	}
	return cuo
}

// ClearLink clears the value of the "link" field.
func (cuo *ClientsUpdateOne) ClearLink() *ClientsUpdateOne {
	cuo.mutation.ClearLink()
	return cuo
}

// SetImageUrl sets the "imageUrl" field.
func (cuo *ClientsUpdateOne) SetImageUrl(s string) *ClientsUpdateOne {
	cuo.mutation.SetImageUrl(s)
	return cuo
}

// SetNillableImageUrl sets the "imageUrl" field if the given value is not nil.
func (cuo *ClientsUpdateOne) SetNillableImageUrl(s *string) *ClientsUpdateOne {
	if s != nil {
		cuo.SetImageUrl(*s)
	}
	return cuo
}

// ClearImageUrl clears the value of the "imageUrl" field.
func (cuo *ClientsUpdateOne) ClearImageUrl() *ClientsUpdateOne {
	cuo.mutation.ClearImageUrl()
	return cuo
}

// SetCreatedAt sets the "created_at" field.
func (cuo *ClientsUpdateOne) SetCreatedAt(t time.Time) *ClientsUpdateOne {
	cuo.mutation.SetCreatedAt(t)
	return cuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cuo *ClientsUpdateOne) SetNillableCreatedAt(t *time.Time) *ClientsUpdateOne {
	if t != nil {
		cuo.SetCreatedAt(*t)
	}
	return cuo
}

// SetUpdatedAt sets the "updated_at" field.
func (cuo *ClientsUpdateOne) SetUpdatedAt(t time.Time) *ClientsUpdateOne {
	cuo.mutation.SetUpdatedAt(t)
	return cuo
}

// Mutation returns the ClientsMutation object of the builder.
func (cuo *ClientsUpdateOne) Mutation() *ClientsMutation {
	return cuo.mutation
}

// Where appends a list predicates to the ClientsUpdate builder.
func (cuo *ClientsUpdateOne) Where(ps ...predicate.Clients) *ClientsUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *ClientsUpdateOne) Select(field string, fields ...string) *ClientsUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Clients entity.
func (cuo *ClientsUpdateOne) Save(ctx context.Context) (*Clients, error) {
	cuo.defaults()
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *ClientsUpdateOne) SaveX(ctx context.Context) *Clients {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *ClientsUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *ClientsUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cuo *ClientsUpdateOne) defaults() {
	if _, ok := cuo.mutation.UpdatedAt(); !ok {
		v := clients.UpdateDefaultUpdatedAt()
		cuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *ClientsUpdateOne) check() error {
	if v, ok := cuo.mutation.Name(); ok {
		if err := clients.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Clients.name": %w`, err)}
		}
	}
	return nil
}

func (cuo *ClientsUpdateOne) sqlSave(ctx context.Context) (_node *Clients, err error) {
	if err := cuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(clients.Table, clients.Columns, sqlgraph.NewFieldSpec(clients.FieldID, field.TypeInt))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Clients.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, clients.FieldID)
		for _, f := range fields {
			if !clients.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != clients.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.Name(); ok {
		_spec.SetField(clients.FieldName, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Link(); ok {
		_spec.SetField(clients.FieldLink, field.TypeString, value)
	}
	if cuo.mutation.LinkCleared() {
		_spec.ClearField(clients.FieldLink, field.TypeString)
	}
	if value, ok := cuo.mutation.ImageUrl(); ok {
		_spec.SetField(clients.FieldImageUrl, field.TypeString, value)
	}
	if cuo.mutation.ImageUrlCleared() {
		_spec.ClearField(clients.FieldImageUrl, field.TypeString)
	}
	if value, ok := cuo.mutation.CreatedAt(); ok {
		_spec.SetField(clients.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := cuo.mutation.UpdatedAt(); ok {
		_spec.SetField(clients.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Clients{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{clients.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
