// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"project-manager/ent/clients"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Clients is the model entity for the Clients schema.
type Clients struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// The name of the package
	Name string `json:"name,omitempty"`
	// The link to the package
	Link string `json:"link,omitempty"`
	// The image URL of the client
	ImageUrl string `json:"imageUrl,omitempty"`
	// The time the package was created
	CreatedAt time.Time `json:"created_at,omitempty"`
	// The time the package was last updated
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Clients) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case clients.FieldID:
			values[i] = new(sql.NullInt64)
		case clients.FieldName, clients.FieldLink, clients.FieldImageUrl:
			values[i] = new(sql.NullString)
		case clients.FieldCreatedAt, clients.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Clients fields.
func (c *Clients) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case clients.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			c.ID = int(value.Int64)
		case clients.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				c.Name = value.String
			}
		case clients.FieldLink:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field link", values[i])
			} else if value.Valid {
				c.Link = value.String
			}
		case clients.FieldImageUrl:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field imageUrl", values[i])
			} else if value.Valid {
				c.ImageUrl = value.String
			}
		case clients.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				c.CreatedAt = value.Time
			}
		case clients.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				c.UpdatedAt = value.Time
			}
		default:
			c.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Clients.
// This includes values selected through modifiers, order, etc.
func (c *Clients) Value(name string) (ent.Value, error) {
	return c.selectValues.Get(name)
}

// Update returns a builder for updating this Clients.
// Note that you need to call Clients.Unwrap() before calling this method if this Clients
// was returned from a transaction, and the transaction was committed or rolled back.
func (c *Clients) Update() *ClientsUpdateOne {
	return NewClientsClient(c.config).UpdateOne(c)
}

// Unwrap unwraps the Clients entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (c *Clients) Unwrap() *Clients {
	_tx, ok := c.config.driver.(*txDriver)
	if !ok {
		panic("ent: Clients is not a transactional entity")
	}
	c.config.driver = _tx.drv
	return c
}

// String implements the fmt.Stringer.
func (c *Clients) String() string {
	var builder strings.Builder
	builder.WriteString("Clients(")
	builder.WriteString(fmt.Sprintf("id=%v, ", c.ID))
	builder.WriteString("name=")
	builder.WriteString(c.Name)
	builder.WriteString(", ")
	builder.WriteString("link=")
	builder.WriteString(c.Link)
	builder.WriteString(", ")
	builder.WriteString("imageUrl=")
	builder.WriteString(c.ImageUrl)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(c.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(c.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ClientsSlice is a parsable slice of Clients.
type ClientsSlice []*Clients
