// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"project-manager/ent/packages"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PackagesCreate is the builder for creating a Packages entity.
type PackagesCreate struct {
	config
	mutation *PackagesMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (pc *PackagesCreate) SetName(s string) *PackagesCreate {
	pc.mutation.SetName(s)
	return pc
}

// SetLink sets the "link" field.
func (pc *PackagesCreate) SetLink(s string) *PackagesCreate {
	pc.mutation.SetLink(s)
	return pc
}

// SetNillableLink sets the "link" field if the given value is not nil.
func (pc *PackagesCreate) SetNillableLink(s *string) *PackagesCreate {
	if s != nil {
		pc.SetLink(*s)
	}
	return pc
}

// SetDescription sets the "description" field.
func (pc *PackagesCreate) SetDescription(s string) *PackagesCreate {
	pc.mutation.SetDescription(s)
	return pc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (pc *PackagesCreate) SetNillableDescription(s *string) *PackagesCreate {
	if s != nil {
		pc.SetDescription(*s)
	}
	return pc
}

// Mutation returns the PackagesMutation object of the builder.
func (pc *PackagesCreate) Mutation() *PackagesMutation {
	return pc.mutation
}

// Save creates the Packages in the database.
func (pc *PackagesCreate) Save(ctx context.Context) (*Packages, error) {
	return withHooks(ctx, pc.sqlSave, pc.mutation, pc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PackagesCreate) SaveX(ctx context.Context) *Packages {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *PackagesCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *PackagesCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *PackagesCreate) check() error {
	if _, ok := pc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Packages.name"`)}
	}
	if v, ok := pc.mutation.Name(); ok {
		if err := packages.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Packages.name": %w`, err)}
		}
	}
	return nil
}

func (pc *PackagesCreate) sqlSave(ctx context.Context) (*Packages, error) {
	if err := pc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	pc.mutation.id = &_node.ID
	pc.mutation.done = true
	return _node, nil
}

func (pc *PackagesCreate) createSpec() (*Packages, *sqlgraph.CreateSpec) {
	var (
		_node = &Packages{config: pc.config}
		_spec = sqlgraph.NewCreateSpec(packages.Table, sqlgraph.NewFieldSpec(packages.FieldID, field.TypeInt))
	)
	if value, ok := pc.mutation.Name(); ok {
		_spec.SetField(packages.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := pc.mutation.Link(); ok {
		_spec.SetField(packages.FieldLink, field.TypeString, value)
		_node.Link = value
	}
	if value, ok := pc.mutation.Description(); ok {
		_spec.SetField(packages.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	return _node, _spec
}

// PackagesCreateBulk is the builder for creating many Packages entities in bulk.
type PackagesCreateBulk struct {
	config
	err      error
	builders []*PackagesCreate
}

// Save creates the Packages entities in the database.
func (pcb *PackagesCreateBulk) Save(ctx context.Context) ([]*Packages, error) {
	if pcb.err != nil {
		return nil, pcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Packages, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PackagesMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *PackagesCreateBulk) SaveX(ctx context.Context) []*Packages {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *PackagesCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *PackagesCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}
