// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"project-manager/ent/projects"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Projects is the model entity for the Projects schema.
type Projects struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// ImageUrl holds the value of the "imageUrl" field.
	ImageUrl string `json:"imageUrl,omitempty"`
	// Link holds the value of the "link" field.
	Link string `json:"link,omitempty"`
	// Description holds the value of the "description" field.
	Description  string `json:"description,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Projects) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case projects.FieldID:
			values[i] = new(sql.NullInt64)
		case projects.FieldName, projects.FieldImageUrl, projects.FieldLink, projects.FieldDescription:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Projects fields.
func (pr *Projects) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case projects.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pr.ID = int(value.Int64)
		case projects.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				pr.Name = value.String
			}
		case projects.FieldImageUrl:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field imageUrl", values[i])
			} else if value.Valid {
				pr.ImageUrl = value.String
			}
		case projects.FieldLink:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field link", values[i])
			} else if value.Valid {
				pr.Link = value.String
			}
		case projects.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				pr.Description = value.String
			}
		default:
			pr.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Projects.
// This includes values selected through modifiers, order, etc.
func (pr *Projects) Value(name string) (ent.Value, error) {
	return pr.selectValues.Get(name)
}

// Update returns a builder for updating this Projects.
// Note that you need to call Projects.Unwrap() before calling this method if this Projects
// was returned from a transaction, and the transaction was committed or rolled back.
func (pr *Projects) Update() *ProjectsUpdateOne {
	return NewProjectsClient(pr.config).UpdateOne(pr)
}

// Unwrap unwraps the Projects entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pr *Projects) Unwrap() *Projects {
	_tx, ok := pr.config.driver.(*txDriver)
	if !ok {
		panic("ent: Projects is not a transactional entity")
	}
	pr.config.driver = _tx.drv
	return pr
}

// String implements the fmt.Stringer.
func (pr *Projects) String() string {
	var builder strings.Builder
	builder.WriteString("Projects(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pr.ID))
	builder.WriteString("name=")
	builder.WriteString(pr.Name)
	builder.WriteString(", ")
	builder.WriteString("imageUrl=")
	builder.WriteString(pr.ImageUrl)
	builder.WriteString(", ")
	builder.WriteString("link=")
	builder.WriteString(pr.Link)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(pr.Description)
	builder.WriteByte(')')
	return builder.String()
}

// ProjectsSlice is a parsable slice of Projects.
type ProjectsSlice []*Projects
