// Code generated by ent, DO NOT EDIT.

package ent

import (
	"project-manager/ent/packages"
	"project-manager/ent/projects"
	"project-manager/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	packagesFields := schema.Packages{}.Fields()
	_ = packagesFields
	// packagesDescName is the schema descriptor for name field.
	packagesDescName := packagesFields[0].Descriptor()
	// packages.NameValidator is a validator for the "name" field. It is called by the builders before save.
	packages.NameValidator = packagesDescName.Validators[0].(func(string) error)
	projectsFields := schema.Projects{}.Fields()
	_ = projectsFields
	// projectsDescName is the schema descriptor for name field.
	projectsDescName := projectsFields[0].Descriptor()
	// projects.NameValidator is a validator for the "name" field. It is called by the builders before save.
	projects.NameValidator = projectsDescName.Validators[0].(func(string) error)
}
