definitions:
  ent.Packages:
    properties:
      created_at:
        description: The time the package was created
        type: string
      description:
        description: A brief description of the package
        type: string
      id:
        description: ID of the ent.
        type: integer
      link:
        description: The link to the package
        type: string
      name:
        description: The name of the package
        type: string
      updated_at:
        description: The time the package was last updated
        type: string
    type: object
  ent.Projects:
    properties:
      description:
        description: Description holds the value of the "description" field.
        type: string
      id:
        description: ID of the ent.
        type: integer
      image_url:
        description: ImageURL holds the value of the "image_url" field.
        type: string
      link:
        description: Link holds the value of the "link" field.
        type: string
      name:
        description: Name holds the value of the "name" field.
        type: string
    type: object
info:
  contact: {}
paths:
  /api/packages:
    get:
      description: Retrieve a list of all packages
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/ent.Packages'
            type: array
      summary: Get all packages
  /api/projects:
    get:
      description: Retrieve a list of all projects
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/ent.Projects'
            type: array
      summary: Get all projects
  /packages/{id}:
    delete:
      description: Delete a package by ID
      parameters:
      - description: packages ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete a package
    get:
      description: |-
        Retrieve a package by its ID
        Retrieve a package by its ID
      parameters:
      - description: Projects ID
        in: path
        name: id
        required: true
        type: integer
      - description: Packages ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ent.Packages'
      summary: Get a package by ID
    put:
      consumes:
      - application/json
      description: Update a package by ID
      parameters:
      - description: Packages ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ent.Packages'
      summary: Update a package
  /projects/{id}:
    delete:
      description: Delete a project by ID
      parameters:
      - description: Projects ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete a project
    get:
      description: |-
        Retrieve a project by its ID
        Retrieve a project by its ID
      parameters:
      - description: Projects ID
        in: path
        name: id
        required: true
        type: integer
      - description: Projects ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ent.Projects'
      summary: Get a project by ID
    put:
      consumes:
      - application/json
      description: Update a project by ID
      parameters:
      - description: Projects ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ent.Projects'
      summary: Update a project
swagger: "2.0"
