// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Clients is the predicate function for clients builders.
type Clients func(*sql.Selector)

// Packages is the predicate function for packages builders.
type Packages func(*sql.Selector)

// Projects is the predicate function for projects builders.
type Projects func(*sql.Selector)
